services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    command: mosquitto -c /mosquitto-no-auth-websocket.conf
    volumes:
      - ./config/mosquitto-no-auth-websocket.conf:/mosquitto-no-auth-websocket.conf
    ports:
      - "1883:1883"
      - "9001:9001"

  subscriber:
    build: .
    container_name: subscriber
    command: ./venv/bin/python -u subscribe.py
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - mosquitto

  stats_subscriber:
    build: .
    container_name: stats_subscriber
    command: ./venv/bin/python -u stats_pubsub.py
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - subscriber

  publisher:
    build: .
    container_name: publisher
    command: ./venv/bin/python -u publish.py
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - mosquitto
      - subscriber
      - stats_subscriber

  web:
    container_name: web
    image: nginx
    volumes:
      - ./www/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    depends_on:
      - mosquitto
      - publisher
